# Generated by Django 5.2.6 on 2025-10-20 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceremony_type', models.CharField(choices=[('Wedding', 'Wedding'), ('Baptism', 'Baptism'), ('Funeral', 'Funeral'), ('Thanksgiving', 'Thanksgiving'), ('Bible Study', 'Bible Study'), ('Youth Meeting', 'Youth Meeting'), ('Other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('officiated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
